### ISSUE TITLE
Undefined reference & extra return?

### ISSUE THREAD

**Issue by ldodds** [kikonen/capybara-ng#13]
I've just started using this library to try to help resolve some issues with an testing angularjs app from Cucumber.

However I'm still getting some problems so have been trying to debug what the library is doing.

I've noticed two unexpected things.

1. Firstly there's [a reference to el](https://github.com/kikonen/capybara-ng/blob/master/lib/angular/waiter.rb#L80) at Line 80 in Waiter which isn't defined. The try..catch block there always jumps to the catch.  Is there a missing line, like: 

```var el = document.querySelector(selector);```

2. In [ClientScript.FN_WaitForAngular there's a return](https://github.com/kikonen/capybara-ng/blob/master/lib/angular/client_script.rb#L15) that means that the try..catch block there is ignored. Presumably its not necessary?

**Comment by ldodds** [comment]
re: the first thing, if I do declare a querySelector, e.g.:

```
var el = document.querySelector('[ng-app], [data-ng-app]');
```

Then the code does start to behave as expected (and later times out from the `ready?` loop in Waiter, which is my actual problem)

**Comment by kikonen** [comment]
Q: Are debug infos enabled in app?

I.e. if there is this, might need to change it
```
$compileProvider.debugInfoEnabled(false);
```

**Comment by ldodds** [comment]
Thanks for merging the other changes. I'm not sure what you mean by enabling debug infos?

The additional code in FN_WaitForAngular isn't causing any specific problems, it just doesn't look correct as it won't ever be executed?

**Comment by kikonen** [comment]
"waitForAngular" is not used for anything so it's not affecting things.

**Comment by kikonen** [comment]
Added some extra tracing into JS code, in case if helps to see what's going on.

**Comment by ldodds** [comment]
OK, happy to close this issue now. The JavaScript fix and logging are helpful. The core ng_wait functionality is now working for me.

If waitForAngular is not used then recommend removing it, but your call! Thanks for responding so quickly.
